travis:
  secure:
    BINSTAR_TOKEN: rPc/4vefleBGZZAYve4iCbHG3JY4MQk131EON88GatrdJrINy2NkLXAp4Vs01G/59w2hjx5qpt88BKKyDh/8FC9xchjCLRwBOjJQpOMOQX278MGsIc4QelNP0FX9Gx7GW/KEBGzyJklRF2tAG0PxageRUMtk6GUFCIPiQfEnyydE442fQOgFA8Z9uwgdOLfZtfIYuOGgNFD7miiiynMTN2jztNBsNXizIbALaje0uZXFiX0Bu6V1wsLFnSEfIaOdWyz5rNmLnCqBEZt5CPBPRr/EB4rbBQCZxYlmvc4lyp0O4k3x5JWNpniwzX84SkbJNW9nWCVDIRjyXvzB070/NiIu5kmB+1MAPJTUCZPRgim0xNR7y1Fy8jNi64VKRcntflCswgQmZ2jutUkgOuLcHKTFkCt8V0v/m/hXOUlnXkZVlo2DPBI72jXHTVAtCErRnCwB8RpzAPCIifXpzJRAx09cAzO7d8Wyf1Z5iXhxSJ2khOzU/wifKSQYM3mcZz+mxHrXIR2VjJoAV7cyJC+aDrIbOLqGtN6ZqnC4j1vMpl89778/o/7ZT0cmC5zOCs+gnGQPop7j+667GVLWdM8VFGsnmHrZI+84UUNjpruulP7wjRmgTZ/KLAYvcrLxT1DoPPkhQ2P4HEhE3EPPcWhRxgdZF04H8eUTRjJXvf3c/fk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
